spring.application.name=jwt-gateway-service
server.port=8080
spring.config.import=optional:classpath:.env
JWT_SECRET_KEY=${JWT_SECRET}
FRONTEND_URL=${FRONT_URL}
X_SECRET_GATEWAY_HEADER=${SECRET_GATEWAY_HEADER}